#!/bin/sh

cp src/dev/resources/META-INF/persistence-wildfly.xml src/dev/resources/META-INF/persistence.xml
cp src/prod/resources/META-INF/persistence-wildfly.xml src/prod/resources/META-INF/persistence.xml
